### ISSUE TITLE
Tracking เกรด

### ISSUE THREAD

**Issue by Witchaz** [karnhao/haolearn#55]
เพิ่มให้แต่ละวิชาเก็บหน่วยกิตและสามารถคำนวณเกรดที่เราต้องการได้

**Comment by karnhao** [comment]
คือเราสามารถตั้งหน่วยกิตของแต่ละวิชาได้ แล้วก็ตั้งว่าแต่ละวิชาเรามีคะแนนเท่าไหร่แล้วใช่มั้ย แล้วเราจะบอกผลสรุปแบบไหนดีในเมื่อเรายังไม่ทราบคะแนนที่ได้

เราอาจจะต้องมีระบบวางแผนคะแนน เช่น วิชาคณิตศาสตร์แบ่งการเก็บคะแนนดังนี้

 - สอบกลางภาค 40%
 - สอบปลายภาค 50%
 - การบ้าน 10%

โดยเราสามารถวางโครงคะแนนให้ก่อนได้ แล้วพอเราได้คะแนนแล้วก็ค่อยเข้ามากรอกคะแนนที่ได้

สรุปเราจะมีฟีเจอร์ดังนี้
 - วางโครงคะแนน
 - กรอกคะแนนที่ได้
 - ตั้งเป้าหมายคะแนนที่เราอยากได้
 - สรุปผลคะแนนรวม
 - ระบบคำนวนเกรดรวมจากทุกวิชา โดยถ้าวิชาใดๆที่ยังกรอกคะแนนไม่ครบตามที่ว่างโครงคะแนนไว้ วิชานั้นจะได้เกรด I

การกำหนดเกรดของโปรแกรมเราจะกำหนดดังนี้

A หมายถึง เกรด 4
B+ หมายถึง เกรด 3.5
B หมายถึง เกรด 3
C+ หมายถึง เกรด 2.5
C หมายถึง เกรด 2
D+ หมายถึง เกรด 1.5
D หมายถึง เกรด 1
F หมายถึง เกรด 0

W หมายถึง ถอนรายวิชา 
X หมายถึง รออาจารย์ส่งคะแนน 
I หมายถึง เกรดยังไม่สมบูรณ์ ต้องสอบหรือส่งงานให้ครบก่อน แล้วถึงจะเปลี่ยนเป็น เกรดมาตรฐาน 
S หมายถึง ผ่าน แบบไม่คิดเกรด(พวกวิชาฝึกงาน)
U หมายถึง ไม่ผ่าน แบบไม่คิดเกรด (พวกวิชาฝึกงาน)
